default_platform(:ios)

desc "Установка зависимостей, сборка с помощью scan"
lane :custom_build_for_testing do |options|
  cocoapods
  swiftlint(
        mode: :lint,
        executable: "Pods/SwiftLint/swiftlint",
    config_file: ".swiftlint.yml",
        ignore_exit_status: false
  )
  scan(
      build_for_testing: true
  )
end

desc "Запуск тестов на уже скомпилированном приложении"
lane :custom_run_tests do |options|
  scan(
    test_without_building: true,
    testplan: 'UnitTestPlan'
  )
  scan(
    test_without_building: true,
    testplan: 'UITestPlan'
  )
end

desc "Вызов первых двух лейнов"
lane :custom_build_and_test do |options|
  custom_build_for_testing
  custom_run_tests
end
